# need to switch to travis trusty (ubuntu 14) images to use openjdk8
dist: trusty
sudo: false

language: java

jdk:
    - openjdk8
#    - oraclejdk8

env:
  - MONGODB_VER=mongodb-linux-x86_64-2.6.12 ANT_TEST=test_no_mongo_storage
#  - MONGODB_VER=mongodb-linux-x86_64-2.6.12 ANT_TEST=test_mongo_storage
#  - MONGODB_VER=mongodb-linux-x86_64-3.0.14 ANT_TEST=test_mongo_storage
#  - MONGODB_VER=mongodb-linux-x86_64-3.2.12 ANT_TEST=test_mongo_storage
#  - MONGODB_VER=mongodb-linux-x86_64-3.4.2  ANT_TEST=test_mongo_storage

before_install:
    # get and install mongodb
    - wget http://fastdl.mongodb.org/linux/$MONGODB_VER.tgz
    - tar xfz $MONGODB_VER.tgz
    - export MONGOD=`pwd`/$MONGODB_VER/bin/mongod

install:
    - cd ..
    - git clone https://github.com/kbase/jars
    - cd -

script:
    - cp -n test.cfg.example test.cfg

    - mkdir temp_test_dir
    # Note: using # as delimiter instead of / since / is in the mongod path
    # If there are # in the mongod path, this will fail.
    - sed -i "s#^test.temp.dir=.*#test.temp.dir=temp_test_dir#" test.cfg

    - sed -i "s#^test.mongo.exe.*#test.mongo.exe=$MONGOD#" test.cfg
    - cat test.cfg
    - ant test-report

after_success:
    - ls docs/test-reports
    - bash <(curl -s https://codecov.io/bash) -t d0459879-5330-46e8-af6b-547c06630ea8 -f docs/test-reports/report.xml

